<template>
    <div ref="container" class="drawing-canvas" style="user-select:none; width:100%; height:100%; text-align: center; display: table;">
        <svg id="canvas"></svg>
    </div>
</template>

<script>

import * as d3 from "d3";

export default {
    data () {
        return {}
    },
    created() {
        console.log('created')
    },
    mounted() {
        var width = this.$refs.container.clientWidth;
        var height = this.$refs.container.clientHeight;
        d3.select("#canvas").attr("width", width).attr("height", height);
        // Generated by CoffeeScript 1.4.0
        (function() {
        var SWATCH_D, active_color, active_line, canvas, drag, drawing_data, lines_layer, palette, redraw, render_line, swatches, trash_btn;
        var lineGenerator = d3.line().curve(d3.curveCardinal);

        SWATCH_D = 22;

        render_line = d3.line().x(function(d) {
            return d[0];
        }).y(function(d) {
            return d[1];
        });

        drawing_data = {
            lines: [
                {
                    color: "#000000",
                    points: []
                }
            ]
        };

        active_line = null;

        active_color = "#333333";

        canvas = d3.select('#canvas');

        lines_layer = canvas.append('g');

        drag = d3.drag();

        drag.on('start', function() {
            active_line = {
            points: [],
            color: active_color
            };
            drawing_data.lines.push(active_line);
            return redraw(active_line);
        });

        drag.on('drag', function() {
            active_line.points.push(d3.mouse(this));
            return redraw(active_line);
        });

        drag.on('end', function() {
            if (active_line.points.length === 0) {
            drawing_data.lines.pop();
            }
            active_line = null;
            return console.log(drawing_data);
        });

        canvas.call(drag);

        redraw = function(specific_line) {
            var lines = lines_layer.selectAll('.line').data(drawing_data.lines);
            var lineEnter = lines.enter().append('path')
                        .attr("class", 'line')
                        .attr("stroke", function(d) { return d.color; })
                        .attr("d", function(d) { return lineGenerator(d.points); });
        
            lineEnter.each(function(d, i) {
                return d.elem = d3.select(this);
            })
            if (specific_line != null) {
                specific_line.elem.attr("d",function(d){ return lineGenerator(d.points); });
            } else {
                // lines.attr({
                //     d: function(d) {
                //         return render_line(d.points);
                //     }
                // });
            }
            return lines.exit().remove();
        };

        redraw();

        }).call(this);

    },
    destroyed() {
        console.log('destroyed')
    }
}
</script>

<style>
#canvas {
  background: oldlace;
}
#ui {
  position: absolute;
  top: 0;
  left: 0;
  pointer-events: none;
}
.swatch {
  pointer-events: all;
}
.swatch.active {
  stroke-width: 2px;
  stroke: black;
}
.swatch {
  cursor: pointer;
}
.btn {
  pointer-events: all;
  
  font-family: FontAwesome;
  fill: #333;
  font-size: 32px;
  text-anchor: middle;
  
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
.btn:hover {
  fill: black;
  cursor: pointer;
}

.line {
  fill: none;
  stroke-width: 2px;
  stroke-linejoin: round;
  stroke-linecap: round;
}
</style>
